
DROP TABLE IF EXISTS PUZZLE_ATTEMPT;
DROP TABLE IF EXISTS COURSE_PROGRESS;
DROP TABLE IF EXISTS DAILY_PUZZLES;
DROP TABLE IF EXISTS CHAPTERS;

DROP TABLE IF EXISTS PUZZLES;
DROP TABLE IF EXISTS COURSES;

DROP TABLE IF EXISTS TAGS;
DROP TABLE IF EXISTS USERS;