-- שליפת כל הנתונים מכל הטבלאות
SELECT * FROM USERS;
SELECT * FROM COURSES;
SELECT * FROM CHAPTERS;
SELECT * FROM TAGS;
SELECT * FROM PUZZLES;
SELECT * FROM DAILY_PUZZLES;
SELECT * FROM COURSE_PROGRESS;
SELECT * FROM PUZZLE_ATTEMPT;

-- ספירת כמות הרשומות בכל טבלה
SELECT 'USERS' AS table_name, COUNT(*) FROM USERS;
SELECT 'COURSES' AS table_name, COUNT(*) FROM COURSES;
SELECT 'CHAPTERS' AS table_name, COUNT(*) FROM CHAPTERS;
SELECT 'TAGS' AS table_name, COUNT(*) FROM TAGS;
SELECT 'PUZZLES' AS table_name, COUNT(*) FROM PUZZLES;
SELECT 'DAILY_PUZZLES' AS table_name, COUNT(*) FROM DAILY_PUZZLES;
SELECT 'COURSE_PROGRESS' AS table_name, COUNT(*) FROM COURSE_PROGRESS;
SELECT 'PUZZLE_ATTEMPT' AS table_name, COUNT(*) FROM PUZZLE_ATTEMPT;