-- ספירת כמות הרשומות בכל טבלה
SELECT 'USERS' AS table_name, COUNT(*) FROM USERS
UNION ALL
SELECT 'COURSES' AS table_name, COUNT(*) FROM COURSES
UNION ALL
SELECT 'CHAPTERS' AS table_name, COUNT(*) FROM CHAPTERS
UNION ALL
SELECT 'TAGS' AS table_name, COUNT(*) FROM TAGS
UNION ALL
SELECT 'PUZZLES' AS table_name, COUNT(*) FROM PUZZLES
UNION ALL
SELECT 'DAILY_PUZZLES' AS table_name, COUNT(*) FROM DAILY_PUZZLES
UNION ALL
SELECT 'COURSE_PROGRESS' AS table_name, COUNT(*) FROM COURSE_PROGRESS
UNION ALL
SELECT 'PUZZLE_ATTEMPT' AS table_name, COUNT(*) FROM PUZZLE_ATTEMPT;