-- שליפת כל הנתונים מכל הטבלאות
SELECT * FROM USERS;
SELECT * FROM COURSES;
SELECT * FROM CHAPTERS;
SELECT * FROM TAGS;
SELECT * FROM PUZZLES;
SELECT * FROM DAILY_PUZZLES;
SELECT * FROM CHAPTER_PROGRESS;
SELECT * FROM PUZZLE_ATTEMPT;